language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules

script: npm run-script build

before_deploy:
- openssl aes-256-cbc -K $encrypted_92a5b1b18fab_key -iv $encrypted_92a5b1b18fab_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- npm run-script ci:import
- npm run-script build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: build
  on:
    branch: master

