language: node_js
node_js:
- '8'
script: npm run-script ci:build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: build
  on:
    branch: master
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_92a5b1b18fab_key -iv $encrypted_92a5b1b18fab_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
